### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by fuzzy76** [kaimallea/csgo#20]
Service-definition from my docker-compose.yml:

```
  csgo:
    env_file: ./data_env/csgo.env
    image: kmallea/csgo:latest
    ports:
      - target: 27015
        published: 27015
        protocol: tcp
        mode: host
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 27020
        published: 27020
        protocol: tcp
        mode: host
      - target: 27020
        published: 27020
        protocol: udp
        mode: host
    restart: unless-stopped
    volumes:
      - "csgo_data:/home/steam/csgo"
```

Log output:
```
csgo_1        | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
csgo_1        | [  0%] Checking for available updates...
csgo_1        | [----] Verifying installation...
csgo_1        | Steam Console Client (c) Valve Corporation
csgo_1        | -- type 'quit' to exit --
csgo_1        | Loading Steam API...Failed to init SDL priority manager: SDL not found
csgo_1        | Failed to set thread priority: per-thread setup failed
csgo_1        | OK.
csgo_1        | Failed to set thread priority: per-thread setup failed
csgo_1        | 
csgo_1        | Connecting anonymously to Steam Public...Loaded client id: 18364441488310737475
csgo_1        | Listening for IPv4 broadcast on: 27036
csgo_1        | Logged in OK
csgo_1        | Waiting for user info...OK
csgo_1        | ERROR! Failed to install app '740' (Disk write failure)
csgo_1        | CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
csgo_1        | CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 3 items discarded.
csgo_1        | /home/steam/start.sh: line 33: /home/steam/csgo/csgo/cfg/autoexec.cfg: No such file or directory
csgo_1        | /home/steam/start.sh: line 44: /home/steam/csgo/csgo/cfg/server.cfg: No such file or directory
csgo_1        | Installing plugins...
csgo_1        | mkdir: cannot create directory ‘/home/steam/csgo/csgo’: Permission denied
csgo_1        | /bin/bash: /home/steam/csgo/srcds_run: No such file or directory
```
