### ISSUE TITLE
Server refuses to start

### ISSUE THREAD

**Issue by fuzzy76** [kaimallea/csgo#62]
This setup used to work, but stopped working some time last year. Even tried removing both container and image and rebuild.

Service definition in compose file:

```
  csgo:
    env_file: ./data_env/csgo.env
    image: kmallea/csgo:latest
    ports:
      - target: 27015
        published: 27015
        protocol: tcp
        mode: host
      - target: 27015
        published: 27015
        protocol: udp
        mode: host
      - target: 27020
        published: 27020
        protocol: tcp
        mode: host
      - target: 27020
        published: 27020
        protocol: udp
        mode: host
    restart: unless-stopped
    volumes:
      - "csgo_data:/home/steam/csgo"
      - "./data_configs/csgo.cfg:/home/steam/csgo/csgo/cfg/server.cfg"
      - "./data_configs/csgo_gamemode_casual_server.cfg:/home/steam/csgo/csgo/cfg/gamemode_casual_server.cfg"
      - "./data_configs/csgo/gamemode_competitive_server.cfg:/home/steam/csgo/csgo/cfg/gamemode_competitive_server.cfg"
```

Docker logs:
```
csgo_1        | [----] Update complete, launching...
csgo_1        | CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 7 items discarded.
csgo_1        | max open descriptors set to 2048
csgo_1        | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
csgo_1        | /tmp/dumps insufficient permissions - delete and recreate
csgo_1        | [  0%] Checking for available updates...
csgo_1        | [----] Verifying installation...
csgo_1        | [  0%] Downloading update...
csgo_1        | [  0%] Checking for available updates...
csgo_1        | [----] Download complete.
csgo_1        | [----] Extracting package...
csgo_1        | [----] Extracting package...
csgo_1        | [----] Extracting package...
csgo_1        | [----] Extracting package...
csgo_1        | [----] Installing update...
csgo_1        | [----] Installing update...
csgo_1        | [----] Installing update...
csgo_1        | [----] Installing update...
csgo_1        | [----] Installing update...
csgo_1        | [----] Installing update...
csgo_1        | [----] Installing update...
csgo_1        | [----] Installing update...
csgo_1        | [----] Cleaning up...
csgo_1        | [----] Update complete, launching Steamcmd...
csgo_1        | max open descriptors set to 2048
csgo_1        | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
csgo_1        | [  0%] Checking for available updates...
csgo_1        | [----] Verifying installation...
csgo_1        | Steam Console Client (c) Valve Corporation - version 1642451655
csgo_1        | -- type 'quit' to exit --
csgo_1        | Loading Steam API...OK
csgo_1        | 
csgo_1        | Connecting anonymously to Steam Public...OK
csgo_1        | Waiting for client config...OK
csgo_1        | Waiting for user info...OK
csgo_1        | Please use force_install_dir before logon!
csgo_1        |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
csgo_1        |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
csgo_1        | Error! App '740' state is 0x202 after update job.
csgo_1        | Installing plugins...
csgo_1        | Plugin mmsource-1.10.7-git971-linux.tar.gz is already installed, skipping
csgo_1        | Plugin sourcemod-1.10.0-git6478-linux.tar.gz is already installed, skipping
csgo_1        | Plugin SteamWorks-git131-linux.tar.gz is already installed, skipping
csgo_1        | Plugin download check FAILED for updater.smx
csgo_1        | Plugin practicemode_1.3.3.zip is already installed, skipping
csgo_1        | Plugin pugsetup_2.0.5.zip is already installed, skipping
csgo_1        | Plugin retakes_0.3.4.zip is already installed, skipping
csgo_1        | Plugin retakes-instadefuse.smx is already installed, skipping
csgo_1        | Plugin retakes_autoplant.smx is already installed, skipping
csgo_1        | Plugin retakes-hud.smx is already installed, skipping
csgo_1        | Finished installing plugins.
csgo_1        | grep: /home/steam/csgo/srcds_run: No such file or directory
csgo_1        | /bin/bash: /home/steam/csgo/srcds_run: No such file or directory
```
